spring:
  data:
    mongodb:
      username: ahmed
      password: ahmed
      host: 192.168.134.3
      port: 27017
      database: customer
      authentication-database: admin
server:
  port: 8090
